// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACgINSMD7BddGxDDNsnw0dKslUhstjXB4',
    appId: '1:671438839191:web:47d949c248eebf25ca78d2',
    messagingSenderId: '671438839191',
    projectId: 'apps-665c1',
    authDomain: 'apps-665c1.firebaseapp.com',
    storageBucket: 'apps-665c1.appspot.com',
    measurementId: 'G-L0GQ9V15NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqALBj3nE2vN3Y1TpAkrsA8clytJPSCUA',
    appId: '1:671438839191:android:9367104fc67bf8c4ca78d2',
    messagingSenderId: '671438839191',
    projectId: 'apps-665c1',
    storageBucket: 'apps-665c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO2-M9GAuURcNup_iMqIerwR5LuW9e-0c',
    appId: '1:671438839191:ios:90585dd29cdd4e8bca78d2',
    messagingSenderId: '671438839191',
    projectId: 'apps-665c1',
    storageBucket: 'apps-665c1.appspot.com',
    iosClientId: '671438839191-0lsgugsff79t7608dd9tjok8e45u34fl.apps.googleusercontent.com',
    iosBundleId: 'br.com.mbi.appfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO2-M9GAuURcNup_iMqIerwR5LuW9e-0c',
    appId: '1:671438839191:ios:90585dd29cdd4e8bca78d2',
    messagingSenderId: '671438839191',
    projectId: 'apps-665c1',
    storageBucket: 'apps-665c1.appspot.com',
    iosClientId: '671438839191-0lsgugsff79t7608dd9tjok8e45u34fl.apps.googleusercontent.com',
    iosBundleId: 'br.com.mbi.appfirebase',
  );
}
